# Funding / sponsorship links for koharu-th.
# Format: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

custom: ['mailto:wanadtapong.earth@outlook.co.th']
