use std::fmt;
use std::str::FromStr;

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Method {
    AppVersion,
    Device,
    GetDocuments,
    ListFontFamilies,
    LlmList,
    LlmReady,
    LlmOffload,
    ProcessCancel,
    GetDocument,
    /// v2 blob-transport variant of `GetDocument`. Returns the
    /// same Document shape but with binaries replaced by hex
    /// `BlobId`s the frontend can fetch via `/blob/:hex`. Frontend
    /// RPC uses this; MCP keeps using `GetDocument` for pixel
    /// access. See docs/v2-arch.md §5 Phase 2 on main.
    GetDocumentDto,
    GetThumbnail,
    ExportDocument,
    ExportAllInpainted,
    ExportAllRendered,
    AddDocuments,
    OpenDocuments,
    OpenExternal,
    Detect,
    Ocr,
    Inpaint,
    UpdateInpaintMask,
    UpdateBrushLayer,
    InpaintPartial,
    Render,
    UpdateTextBlocks,
    UpdateTextBlock,
    TextBlockFitToBubble,
    LlmLoad,
    LlmGenerate,
    Process,
    // Phase 1: project lifecycle
    ProjectCreate,
    ProjectCreatePicker,
    ProjectOpen,
    ProjectOpenPicker,
    ProjectClose,
    ProjectCurrent,
    ProjectBackupPicker,
    RecentProjectsList,
    RecentProjectsRemove,
    // Storage management (Settings → Storage panel + NSIS uninstall hook)
    AppStorageStats,
    AppStorageClear,
    // Phase 4.7: engine system surface — list of registered engines
    // + hardware probe snapshot for the Engine Profile sidebar UI.
    EnginesList,
    HardwareDetected,
    // F4.C: machine-wide engine profile persistence (active engine
    // per artifact slot + per-engine setting overrides).
    EngineProfileGet,
    EngineProfileSet,
    // Audit #6/P2: granular profile mutations — atomic per-key
    // updates that don't suffer the "stale full-profile snapshot
    // trampling" race the bulk `EngineProfileSet` exposed.
    EngineProfileSetActive,
    EngineProfileSetSetting,
    EngineProfileClearSetting,
    // Phase 5.4: undo/redo surface backed by ProjectSession history.
    SessionUndo,
    SessionRedo,
    SessionHistoryState,
    SessionHistoryRecent,
    // Phase 2: series metadata + chapter index
    SeriesMetaGet,
    SeriesMetaUpdate,
    ChaptersList,
    ChapterCreate,
    ChapterAddPages,
    ChapterOpen,
    ChapterGetPageBytes,
    ChapterUpdate,
    ChapterRemove,
    ChapterClearPages,
    ChapterExportCbz,
    // Phase 3: characters + glossary
    CharactersList,
    CharacterAdd,
    CharacterUpdate,
    CharacterRemove,
    GlossaryList,
    GlossaryAdd,
    GlossaryBulkAdd,
    GlossaryUpdate,
    GlossaryRemove,
    GlossaryBumpUsage,
    // Phase 4: prompt templates + rendering
    PromptTemplatesList,
    PromptTemplateAdd,
    PromptTemplateUpdate,
    PromptTemplateRemove,
    PromptRender,
    // Phase 6: translation memory
    TmLookup,
    TmLookupFuzzy,
    TmInsert,
    TmExportTmx,
    TmImportTmx,
    TmPendingEmbeddings,
    TmPendingCount,
    TmSetEmbedding,
    TmLookupSemantic,
    // Phase 9: provider profiles
    ProviderProfilesList,
    ProviderProfileAdd,
    ProviderProfileUpdate,
    ProviderProfileRemove,
    ProviderProfileSecretGet,
    // Phase 10: LLM call log + stats
    LlmCallLog,
    LlmCostStats,
    LlmCostBreakdown,
    // AI Chat
    ChatMessagesList,
    ChatMessageAdd,
    ChatMessageDelete,
    ChatMessagesDeleteFrom,
    ChatMessagesClear,
    WebFetchUrl,
    // Translation queue
    QueueList,
    QueueEnqueue,
    QueueCancel,
    QueueClearFinished,
}

impl Method {
    pub const ALL: &[Method] = &[
        Method::AppVersion,
        Method::Device,
        Method::GetDocuments,
        Method::ListFontFamilies,
        Method::LlmList,
        Method::LlmReady,
        Method::LlmOffload,
        Method::ProcessCancel,
        Method::GetDocument,
        Method::GetDocumentDto,
        Method::GetThumbnail,
        Method::ExportDocument,
        Method::ExportAllInpainted,
        Method::ExportAllRendered,
        Method::AddDocuments,
        Method::OpenDocuments,
        Method::OpenExternal,
        Method::Detect,
        Method::Ocr,
        Method::Inpaint,
        Method::UpdateInpaintMask,
        Method::UpdateBrushLayer,
        Method::InpaintPartial,
        Method::Render,
        Method::UpdateTextBlocks,
        Method::UpdateTextBlock,
        Method::TextBlockFitToBubble,
        Method::LlmLoad,
        Method::LlmGenerate,
        Method::Process,
        Method::ProjectCreate,
        Method::ProjectCreatePicker,
        Method::ProjectOpen,
        Method::ProjectOpenPicker,
        Method::ProjectClose,
        Method::ProjectCurrent,
        Method::ProjectBackupPicker,
        Method::RecentProjectsList,
        Method::RecentProjectsRemove,
        Method::AppStorageStats,
        Method::AppStorageClear,
        Method::EnginesList,
        Method::HardwareDetected,
        Method::EngineProfileGet,
        Method::EngineProfileSet,
        Method::EngineProfileSetActive,
        Method::EngineProfileSetSetting,
        Method::EngineProfileClearSetting,
        Method::SessionUndo,
        Method::SessionRedo,
        Method::SessionHistoryState,
        Method::SessionHistoryRecent,
        Method::SeriesMetaGet,
        Method::SeriesMetaUpdate,
        Method::ChaptersList,
        Method::ChapterCreate,
        Method::ChapterAddPages,
        Method::ChapterOpen,
        Method::ChapterGetPageBytes,
        Method::ChapterUpdate,
        Method::ChapterRemove,
        Method::ChapterClearPages,
        Method::ChapterExportCbz,
        Method::CharactersList,
        Method::CharacterAdd,
        Method::CharacterUpdate,
        Method::CharacterRemove,
        Method::GlossaryList,
        Method::GlossaryAdd,
        Method::GlossaryBulkAdd,
        Method::GlossaryUpdate,
        Method::GlossaryRemove,
        Method::GlossaryBumpUsage,
        Method::PromptTemplatesList,
        Method::PromptTemplateAdd,
        Method::PromptTemplateUpdate,
        Method::PromptTemplateRemove,
        Method::PromptRender,
        Method::TmLookup,
        Method::TmLookupFuzzy,
        Method::TmInsert,
        Method::TmExportTmx,
        Method::TmImportTmx,
        Method::TmPendingEmbeddings,
        Method::TmPendingCount,
        Method::TmSetEmbedding,
        Method::TmLookupSemantic,
        Method::ProviderProfilesList,
        Method::ProviderProfileAdd,
        Method::ProviderProfileUpdate,
        Method::ProviderProfileRemove,
        Method::ProviderProfileSecretGet,
        Method::LlmCallLog,
        Method::LlmCostStats,
        Method::LlmCostBreakdown,
        Method::ChatMessagesList,
        Method::ChatMessageAdd,
        Method::ChatMessageDelete,
        Method::ChatMessagesDeleteFrom,
        Method::ChatMessagesClear,
        Method::WebFetchUrl,
        Method::QueueList,
        Method::QueueEnqueue,
        Method::QueueCancel,
        Method::QueueClearFinished,
    ];

    pub fn as_str(self) -> &'static str {
        match self {
            Method::AppVersion => "app_version",
            Method::Device => "device",
            Method::GetDocuments => "get_documents",
            Method::ListFontFamilies => "list_font_families",
            Method::LlmList => "llm_list",
            Method::LlmReady => "llm_ready",
            Method::LlmOffload => "llm_offload",
            Method::ProcessCancel => "process_cancel",
            Method::GetDocument => "get_document",
            Method::GetDocumentDto => "get_document_dto",
            Method::GetThumbnail => "get_thumbnail",
            Method::ExportDocument => "export_document",
            Method::ExportAllInpainted => "export_all_inpainted",
            Method::ExportAllRendered => "export_all_rendered",
            Method::AddDocuments => "add_documents",
            Method::OpenDocuments => "open_documents",
            Method::OpenExternal => "open_external",
            Method::Detect => "detect",
            Method::Ocr => "ocr",
            Method::Inpaint => "inpaint",
            Method::UpdateInpaintMask => "update_inpaint_mask",
            Method::UpdateBrushLayer => "update_brush_layer",
            Method::InpaintPartial => "inpaint_partial",
            Method::Render => "render",
            Method::UpdateTextBlocks => "update_text_blocks",
            Method::UpdateTextBlock => "update_text_block",
            Method::TextBlockFitToBubble => "text_block_fit_to_bubble",
            Method::LlmLoad => "llm_load",
            Method::LlmGenerate => "llm_generate",
            Method::Process => "process",
            Method::ProjectCreate => "project_create",
            Method::ProjectCreatePicker => "project_create_picker",
            Method::ProjectOpen => "project_open",
            Method::ProjectOpenPicker => "project_open_picker",
            Method::ProjectClose => "project_close",
            Method::ProjectCurrent => "project_current",
            Method::ProjectBackupPicker => "project_backup_picker",
            Method::RecentProjectsList => "recent_projects_list",
            Method::RecentProjectsRemove => "recent_projects_remove",
            Method::AppStorageStats => "app_storage_stats",
            Method::AppStorageClear => "app_storage_clear",
            Method::EnginesList => "engines_list",
            Method::HardwareDetected => "hardware_detected",
            Method::EngineProfileGet => "engine_profile_get",
            Method::EngineProfileSet => "engine_profile_set",
            Method::EngineProfileSetActive => "engine_profile_set_active",
            Method::EngineProfileSetSetting => "engine_profile_set_setting",
            Method::EngineProfileClearSetting => "engine_profile_clear_setting",
            Method::SessionUndo => "session_undo",
            Method::SessionRedo => "session_redo",
            Method::SessionHistoryState => "session_history_state",
            Method::SessionHistoryRecent => "session_history_recent",
            Method::SeriesMetaGet => "series_meta_get",
            Method::SeriesMetaUpdate => "series_meta_update",
            Method::ChaptersList => "chapters_list",
            Method::ChapterCreate => "chapter_create",
            Method::ChapterAddPages => "chapter_add_pages",
            Method::ChapterOpen => "chapter_open",
            Method::ChapterGetPageBytes => "chapter_get_page_bytes",
            Method::ChapterUpdate => "chapter_update",
            Method::ChapterRemove => "chapter_remove",
            Method::ChapterClearPages => "chapter_clear_pages",
            Method::ChapterExportCbz => "chapter_export_cbz",
            Method::CharactersList => "characters_list",
            Method::CharacterAdd => "character_add",
            Method::CharacterUpdate => "character_update",
            Method::CharacterRemove => "character_remove",
            Method::GlossaryList => "glossary_list",
            Method::GlossaryAdd => "glossary_add",
            Method::GlossaryBulkAdd => "glossary_bulk_add",
            Method::GlossaryUpdate => "glossary_update",
            Method::GlossaryRemove => "glossary_remove",
            Method::GlossaryBumpUsage => "glossary_bump_usage",
            Method::PromptTemplatesList => "prompt_templates_list",
            Method::PromptTemplateAdd => "prompt_template_add",
            Method::PromptTemplateUpdate => "prompt_template_update",
            Method::PromptTemplateRemove => "prompt_template_remove",
            Method::PromptRender => "prompt_render",
            Method::TmLookup => "tm_lookup",
            Method::TmLookupFuzzy => "tm_lookup_fuzzy",
            Method::TmInsert => "tm_insert",
            Method::TmExportTmx => "tm_export_tmx",
            Method::TmImportTmx => "tm_import_tmx",
            Method::TmPendingEmbeddings => "tm_pending_embeddings",
            Method::TmPendingCount => "tm_pending_count",
            Method::TmSetEmbedding => "tm_set_embedding",
            Method::TmLookupSemantic => "tm_lookup_semantic",
            Method::ProviderProfilesList => "provider_profiles_list",
            Method::ProviderProfileAdd => "provider_profile_add",
            Method::ProviderProfileUpdate => "provider_profile_update",
            Method::ProviderProfileRemove => "provider_profile_remove",
            Method::ProviderProfileSecretGet => "provider_profile_secret_get",
            Method::LlmCallLog => "llm_call_log",
            Method::LlmCostStats => "llm_cost_stats",
            Method::LlmCostBreakdown => "llm_cost_breakdown",
            Method::ChatMessagesList => "chat_messages_list",
            Method::ChatMessageAdd => "chat_message_add",
            Method::ChatMessageDelete => "chat_message_delete",
            Method::ChatMessagesDeleteFrom => "chat_messages_delete_from",
            Method::ChatMessagesClear => "chat_messages_clear",
            Method::WebFetchUrl => "web_fetch_url",
            Method::QueueList => "queue_list",
            Method::QueueEnqueue => "queue_enqueue",
            Method::QueueCancel => "queue_cancel",
            Method::QueueClearFinished => "queue_clear_finished",
        }
    }
}

impl fmt::Display for Method {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

impl FromStr for Method {
    type Err = anyhow::Error;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let method = match s {
            "app_version" => Method::AppVersion,
            "device" => Method::Device,
            "get_documents" => Method::GetDocuments,
            "list_font_families" => Method::ListFontFamilies,
            "llm_list" => Method::LlmList,
            "llm_ready" => Method::LlmReady,
            "llm_offload" => Method::LlmOffload,
            "process_cancel" => Method::ProcessCancel,
            "get_document" => Method::GetDocument,
            "get_document_dto" => Method::GetDocumentDto,
            "get_thumbnail" => Method::GetThumbnail,
            "export_document" => Method::ExportDocument,
            "export_all_inpainted" => Method::ExportAllInpainted,
            "export_all_rendered" => Method::ExportAllRendered,
            "add_documents" => Method::AddDocuments,
            "open_documents" => Method::OpenDocuments,
            "open_external" => Method::OpenExternal,
            "detect" => Method::Detect,
            "ocr" => Method::Ocr,
            "inpaint" => Method::Inpaint,
            "update_inpaint_mask" => Method::UpdateInpaintMask,
            "update_brush_layer" => Method::UpdateBrushLayer,
            "inpaint_partial" => Method::InpaintPartial,
            "render" => Method::Render,
            "update_text_blocks" => Method::UpdateTextBlocks,
            "update_text_block" => Method::UpdateTextBlock,
            "text_block_fit_to_bubble" => Method::TextBlockFitToBubble,
            "llm_load" => Method::LlmLoad,
            "llm_generate" => Method::LlmGenerate,
            "process" => Method::Process,
            "project_create" => Method::ProjectCreate,
            "project_create_picker" => Method::ProjectCreatePicker,
            "project_open" => Method::ProjectOpen,
            "project_open_picker" => Method::ProjectOpenPicker,
            "project_close" => Method::ProjectClose,
            "project_current" => Method::ProjectCurrent,
            "project_backup_picker" => Method::ProjectBackupPicker,
            "recent_projects_list" => Method::RecentProjectsList,
            "recent_projects_remove" => Method::RecentProjectsRemove,
            "app_storage_stats" => Method::AppStorageStats,
            "app_storage_clear" => Method::AppStorageClear,
            "engines_list" => Method::EnginesList,
            "hardware_detected" => Method::HardwareDetected,
            "engine_profile_get" => Method::EngineProfileGet,
            "engine_profile_set" => Method::EngineProfileSet,
            "engine_profile_set_active" => Method::EngineProfileSetActive,
            "engine_profile_set_setting" => Method::EngineProfileSetSetting,
            "engine_profile_clear_setting" => Method::EngineProfileClearSetting,
            "session_undo" => Method::SessionUndo,
            "session_redo" => Method::SessionRedo,
            "session_history_state" => Method::SessionHistoryState,
            "session_history_recent" => Method::SessionHistoryRecent,
            "series_meta_get" => Method::SeriesMetaGet,
            "series_meta_update" => Method::SeriesMetaUpdate,
            "chapters_list" => Method::ChaptersList,
            "chapter_create" => Method::ChapterCreate,
            "chapter_add_pages" => Method::ChapterAddPages,
            "chapter_open" => Method::ChapterOpen,
            "chapter_get_page_bytes" => Method::ChapterGetPageBytes,
            "chapter_update" => Method::ChapterUpdate,
            "chapter_remove" => Method::ChapterRemove,
            "chapter_clear_pages" => Method::ChapterClearPages,
            "chapter_export_cbz" => Method::ChapterExportCbz,
            "characters_list" => Method::CharactersList,
            "character_add" => Method::CharacterAdd,
            "character_update" => Method::CharacterUpdate,
            "character_remove" => Method::CharacterRemove,
            "glossary_list" => Method::GlossaryList,
            "glossary_add" => Method::GlossaryAdd,
            "glossary_bulk_add" => Method::GlossaryBulkAdd,
            "glossary_update" => Method::GlossaryUpdate,
            "glossary_remove" => Method::GlossaryRemove,
            "glossary_bump_usage" => Method::GlossaryBumpUsage,
            "prompt_templates_list" => Method::PromptTemplatesList,
            "prompt_template_add" => Method::PromptTemplateAdd,
            "prompt_template_update" => Method::PromptTemplateUpdate,
            "prompt_template_remove" => Method::PromptTemplateRemove,
            "prompt_render" => Method::PromptRender,
            "tm_lookup" => Method::TmLookup,
            "tm_lookup_fuzzy" => Method::TmLookupFuzzy,
            "tm_insert" => Method::TmInsert,
            "tm_export_tmx" => Method::TmExportTmx,
            "tm_import_tmx" => Method::TmImportTmx,
            "tm_pending_embeddings" => Method::TmPendingEmbeddings,
            "tm_pending_count" => Method::TmPendingCount,
            "tm_set_embedding" => Method::TmSetEmbedding,
            "tm_lookup_semantic" => Method::TmLookupSemantic,
            "provider_profiles_list" => Method::ProviderProfilesList,
            "provider_profile_add" => Method::ProviderProfileAdd,
            "provider_profile_update" => Method::ProviderProfileUpdate,
            "provider_profile_remove" => Method::ProviderProfileRemove,
            "provider_profile_secret_get" => Method::ProviderProfileSecretGet,
            "llm_call_log" => Method::LlmCallLog,
            "llm_cost_stats" => Method::LlmCostStats,
            "llm_cost_breakdown" => Method::LlmCostBreakdown,
            "chat_messages_list" => Method::ChatMessagesList,
            "chat_message_add" => Method::ChatMessageAdd,
            "chat_message_delete" => Method::ChatMessageDelete,
            "chat_messages_delete_from" => Method::ChatMessagesDeleteFrom,
            "chat_messages_clear" => Method::ChatMessagesClear,
            "web_fetch_url" => Method::WebFetchUrl,
            "queue_list" => Method::QueueList,
            "queue_enqueue" => Method::QueueEnqueue,
            "queue_cancel" => Method::QueueCancel,
            "queue_clear_finished" => Method::QueueClearFinished,
            _ => anyhow::bail!("Unknown method: {s}"),
        };
        Ok(method)
    }
}

#[cfg(test)]
mod tests {
    use super::Method;

    #[test]
    fn round_trip() {
        for method in Method::ALL {
            let parsed: Method = method.as_str().parse().expect("method should parse");
            assert_eq!(*method, parsed);
        }
    }
}
