name: Test

on:
  push:
    branches: ['main']
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Integration tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2
        with:
          cache-targets: false
      - uses: ilammy/msvc-dev-cmd@v1
      - run: cargo test --no-run
      - run: cargo test --workspace --tests
